export const GET_PIPELINE = 'GET_PIPELINE';
export const SELECT_PRODUCT = 'SELECT_PRODUCT';
export const UPDATE_PAPERWORK = 'UPDATE_PAPERWORK';
export const UPDATE_SAMPLE = 'UPDATE_SAMPLE';
export const UPDATE_INFOREQUIRED = 'UPDATE_INFOREQUIRED';
export const UPDATE_PHASE = 'UPDATE_PHASE';
export const UPDATE_VENDORPROFILE = 'UPDATE_VENDORPROFILE';
export const UPDATE_WEBPO = 'UPDATE_WEBPO';
export const UPDATE_LABEL = 'UPDATE_LABEL';
export const UPDATE_NTP = 'UPDATE_NTP';

export const GET_PRODUCT = 'GET_PRODUCT';
export const PROFILE_ERROR = 'PROFILE_ERROR';

export const UPDATE_PIPELINE = 'UPDATE_PIPELINE';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const PIPELINE_ERROR = 'PIPELINE_ERROR';
export const CLEAR_PIPELINE = 'CLEAR_PIPELINE';
